[project]
name = "ShortUrl"
version = "1.0.0"
description = "url단축 서비스 api입니다."

[dependencies]
fastapi = "0.110.0"
pytest = "8.1.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
python_files = ["test_*.py"]
markers = [
    "unit"
]

